// Interfaces comunes primero
export { ApiResponse, ApiErrorResponse } from './common.interface';

// Zona Reparto - Sistema de gestión de zonas de entrega
export * from './zona-reparto.interface';

// Zona Distrito - Sistema de asignación de zonas a distritos
export * from './zona-distrito.interface';

// Horario Zona - Sistema de gestión de horarios por zona de reparto - Exportaciones específicas para evitar conflictos
export {
  HorarioZona,
  ZonaRepartoHorario,
  EstadoActualHorario,
  CreateHorarioZonaDto,
  UpdateHorarioZonaDto,
  FiltrosHorarioZona,
  HorarioZonaResponse,
  HorariosZonaResponse,
  EstadisticasHorarioZona,
  HorariosPorZona,
  HorariosPorDia,
  ResumenCoberturaSemanal,
  AnalisisDisponibilidad,
  DiaSemana,
  DIAS_SEMANA,
  OPCIONES_ORDEN_HORARIO,
  DIRECCIONES_ORDEN_HORARIO,
  FRANJAS_HORARIAS,
  OpcionOrdenHorario,
  DireccionOrdenHorario,
  FranjaHoraria,
  validarHorarioZona,
  validarFormatoHora,
  convertirHoraAMinutos,
  convertirMinutosAHora,
  obtenerDiaInfo,
  obtenerDiaPorNumero,
  formatearHorario,
  formatearDuracion,
  calcularDuracion,
  esHorarioValido,
  estaAbiertoAhora,
  obtenerDiaActual,
  agruparPorZona as agruparHorariosPorZona,
  agruparPorDia as agruparHorariosPorDia,
  calcularEstadisticas as calcularEstadisticasHorarios,
  filtrarPorZona as filtrarHorariosPorZona,
  filtrarPorDia as filtrarHorariosPorDia,
  filtrarActivos as filtrarHorariosActivos,
  filtrarInactivos as filtrarHorariosInactivos,
  filtrarDiaCompleto,
  filtrarHorariosParciales,
  filtrarAbiertosAhora,
  filtrarPorFranja,
  ordenarPorDia as ordenarHorariosPorDia,
  ordenarPorHora,
  ordenarPorDuracion,
  buscarHorarios,
  validarHorarioUnico,
  detectarConflictosHorarios,
  generarResumenCobertura as generarResumenCoberturaHorarios,
  analizarDisponibilidad,
  obtenerFranjaHoraria,
  formatearHorarioCompleto,
  obtenerProximoHorario,
  calcularTiempoHastaProximaApertura,
} from './horario-zona.interface';

// Departamento - Sistema de división territorial
export * from './departamento.interface';

// Provincia - Sistema de división territorial - Exportaciones específicas para evitar conflictos
export {
  Provincia,
  DepartamentoBasico as DepartamentoBasicoProvincia,
  DistritoBasico,
  EstadisticasProvincia,
  CreateProvinciaRequest,
  UpdateProvinciaRequest,
  ProvinciaFilters,
  ProvinciaPorDepartamentoRequest,
  ProvinciaPorDepartamentoResponse,
  EstadisticasProvinciaGeneral,
  DepartamentoProvincia,
  EstadisticasProvinciaRequest,
  ProvinciaResponse,
  ProvinciaListResponse,
  ProvinciaSimpleListResponse,
  EstadisticasProvinciaResponse,
  ProvinciaErrorResponse,
  ProvinciaFormData,
  PROVINCIA_VALIDATION,
  PROVINCIA_SORT_OPTIONS,
  PROVINCIA_ERROR_MESSAGES,
  PROVINCIA_SUCCESS_MESSAGES,
  ProvinciaSortOption,
  getProvinciaStatusText,
  getProvinciaStatusColor,
  formatCodigoInei as formatCodigoIneiProvincia,
  getProvinciaDisplayName,
  getProvinciaFullName,
  canDeleteProvincia,
  canActivateProvincia,
  getProvinciaEstadisticas,
  getProvinciaEstadisticasResumidas,
  isDepartamentoActivo,
  getProvinciaCodigoCompleto,
  validateProvinciaCanBeActivated,
  validateProvinciaCanBeDeleted,
  getProvinciaSearchableText,
  sortProvinciasByDepartamento,
  groupProvinciasByDepartamento,
  getProvinciasByEstado,
  getProvinciasConDistritos,
  getProvinciasConDelivery,
} from './provincia.interface';

// Distrito - Sistema de división territorial - Exportaciones específicas para evitar conflictos
export {
  Distrito,
  Coordenadas,
  ProvinciaBasica as ProvinciaBasicaDistrito,
  DepartamentoBasico as DepartamentoBasicoDistrito,
  ZonaRepartoBasica,
  EstadisticasDistrito,
  CreateDistritoRequest,
  UpdateDistritoRequest,
  DistritoFilters,
  DistritoPorProvinciaRequest,
  DistritoPorProvinciaResponse,
  DistritosDisponiblesDeliveryResponse,
  ProvinciasConDistritos,
  BuscarPorCoordenadasRequest,
  BuscarPorCoordenadasResponse,
  EstadisticasDistritoGeneral,
  ProvinciaDistrito,
  EstadisticasDistritoRequest,
  DistritoResponse,
  DistritoListResponse,
  DistritoSimpleListResponse,
  EstadisticasDistritoResponse,
  DistritoErrorResponse,
  DistritoFormData,
  DISTRITO_VALIDATION,
  DISTRITO_SORT_OPTIONS,
  DISTRITO_ERROR_MESSAGES,
  DISTRITO_SUCCESS_MESSAGES,
  DistritoSortOption,
  getDistritoStatusText,
  getDistritoStatusColor,
  getDistritoDeliveryText,
  getDistritoDeliveryColor,
  formatCodigoIneiDistrito,
  formatCodigoPostal,
  getDistritoDisplayName,
  getDistritoFullName,
  getDistritoUbicacionCompleta,
  hasCoordinates,
  getCoordinatesDisplay,
  canDeleteDistrito,
  canActivateDistrito,
  canActivateDelivery,
  getDistritoEstadisticas,
  getDistritoEstadisticasResumidas,
  isProvinciaActiva,
  isDepartamentoActivo as isDepartamentoActivoDistrito,
  getDistritoCodigoCompleto,
  validateDistritoCanBeActivated,
  validateDistritoCanBeDeleted,
  validateDeliveryCanBeActivated,
  getDistritoSearchableText,
  sortDistritosByProvincia,
  groupDistritosByProvincia,
  groupDistritosByDepartamento,
  getDistritosByEstado,
  getDistritosConDelivery,
  getDistritosConCoordenadas,
  getDistritosSinCoordenadas,
  getDistritosConZonasReparto,
  calculateDistance,
  findNearestDistritos,
  validateCoordinates,
  formatDistanceDisplay,
  getDistritoIcon,
  getDistritoIconColor,
} from './distrito.interface';

// Costo Envío Dinámico - Sistema de costos de envío por distancia - Exportaciones específicas para evitar conflictos
export {
  CostoEnvioDinamico,
  ZonaRepartoCosto,
  ValidacionesCosto,
  CreateCostoEnvioDinamicoDto,
  UpdateCostoEnvioDinamicoDto,
  FiltrosCostoEnvioDinamico,
  CostoEnvioDinamicoResponse,
  CostosEnvioDinamicoResponse,
  EstadisticasCostoEnvioDinamico,
  CostosPorZona,
  AnalisisCobertura,
  CalculoCosto,
  OptimizacionRangos,
  OPCIONES_ORDEN_COSTO,
  RANGOS_DISTANCIA_COMUNES,
  RANGOS_COSTO_ANALISIS,
  OpcionOrdenCosto,
  DireccionOrdenCosto,
  validarCostoEnvioDinamico,
  detectarSolapamiento,
  encontrarGaps,
  encontrarSolapamientos,
  calcularCostoParaDistancia,
  obtenerCostoMasEconomico,
  obtenerCostoMasRapido,
  agruparPorZona as agruparCostosPorZona,
  filtrarPorZona as filtrarCostosPorZona,
  filtrarPorRangoDistancia,
  filtrarActivos as filtrarCostosActivos,
  filtrarInactivos as filtrarCostosInactivos,
  ordenarPorDistancia,
  ordenarPorAmplitud,
  buscarCostos,
  validarRangoUnico,
  generarSugerenciasOptimizacion,
  analizarCobertura,
  formatearDistancia,
  formatearCosto as formatearCostoCosto,
  formatearRangoDistancia,
  calcularAmplitudRango,
  esRangoValido,
} from './costo-envio-dinamico.interface';

// Producto interfaces - Sistema de productos completo
export * from './producto.interface';

// Otros modelos básicos
export * from './configuracion.model';
export * from './banner.model';
export * from './user.model';
export * from './auth.model';
export * from './atributo.model';

// Cliente - Exportaciones específicas para evitar conflictos
export {
  Cliente,
  ClienteSimple,
  CreateClienteRequest,
  UpdateClienteRequest,
  ClienteFilters,
  ClienteListResponse,
  ClienteCollectionResponse,
  ClienteResponse,
  ClienteStatistics,
  ClienteStatisticsResponse,
  CambiarEstadoRequest,
  Usuario,
  ClientePreferencias,
  ClienteMetadata,
  ClienteResumen,
  EstadoCliente,
  GeneroCliente,
  CLIENTE_SORT_FIELDS,
  type ClienteSortField,
} from './cliente.interface';

// Datos de Facturación - Exportaciones específicas para evitar conflictos
export {
  DatosFacturacion as DatosFacturacionInterface,
  ClienteBasico,
  TipoDocumentoInfo,
  DatosFacturacionComprobante,
  DatosFacturacionResumen,
  CreateDatosFacturacionRequest,
  UpdateDatosFacturacionRequest,
  DatosFacturacionFilters,
  DatosFacturacionByClienteFilters,
  DatosFacturacionListResponse,
  DatosFacturacionCollectionResponse,
  DatosFacturacionResponse,
  DatosFacturacionByClienteResponse,
  DatosFacturacionStatistics,
  DatosFacturacionStatisticsResponse,
  ValidarDocumentoRequest,
  ValidarDocumentoResponse,
  TipoDocumento as TipoDocumentoFacturacion,
  DATOS_FACTURACION_SORT_FIELDS,
  TIPOS_DOCUMENTO_OPCIONES,
  VALIDACIONES_DOCUMENTO,
  CAMPOS_REQUERIDOS_POR_TIPO,
  esTipoEmpresa,
  esPersonaNatural,
  validarDocumento,
  limpiarDocumento,
  formatearDocumento,
  type DatosFacturacionSortField,
} from './datos-facturacion.interface';

// Direcciones - Exportaciones específicas para evitar conflictos
export {
  Direccion,
  Coordenadas as CoordenadasDireccion,
  DireccionCompletaDetallada,
  UbicacionEspecifica,
  DistritoDetalle,
  ProvinciaDetalle,
  DepartamentoDetalle,
  UsuarioDireccion,
  DireccionValidada,
  ZonaRepartoBasica as ZonaRepartoBasicaDireccion,
  ValidacionesDireccion,
  UbicacionDireccion,
  CreateDireccionDto,
  UpdateDireccionDto,
  DireccionFilters,
  DireccionResponse,
  DireccionSingleResponse,
  DireccionesByUsuarioResponse,
  EstadisticasDirecciones,
  DireccionOperationResponse,
  BuscarPorProximidadRequest,
  BuscarPorProximidadResponse,
  DireccionesPorDistritoResponse,
  ActualizarCoordenadasRequest,
  DireccionValidation,
  PaisEnum,
  DIRECCION_VALIDATION,
  DIRECCION_ERROR_MESSAGES,
  DIRECCION_SUCCESS_MESSAGES,
  getDireccionCompleta,
  tieneCoordenadasValidas,
  esDireccionCompleta,
  esValidaParaDelivery,
  getDistritoNombre,
  getProvinciaNombre,
  getDepartamentoNombre,
  formatearAlias,
  calcularDistancia,
} from './direccion.interface';

// Exportaciones específicas para evitar conflictos
export {
  ValorAtributo,
  CreateValorAtributoRequest,
  UpdateValorAtributoRequest,
  ValorAtributoFilters,
  ValorAtributoStatistics,
  PaginatedValorAtributoResponse,
} from './valor-atributo.interface';

export { Cupon, CuponFormData, TipoCupon } from './cupon.model';

export { Categoria as CategoriaModel } from './categoria.model';

// Métodos de Pago - Exportaciones específicas para evitar conflictos
export {
  MetodoPago as MetodoPagoModel,
  CreateMetodoPagoRequest,
  UpdateMetodoPagoRequest,
  MetodoPagoFilters,
  MetodoPagoForSelect,
  CalcularComisionRequest,
  CalcularComisionResponse,
  EstadisticasMetodoPago,
  ValidarMetodoPagoRequest,
  ValidarMetodoPagoResponse,
  ObtenerMetodosPagoRequest,
  ObtenerMetodosPagoResponse,
  MetodoPagoResponse,
  MetodoPagoListResponse,
  MetodoPagoForSelectResponse,
  EstadisticasMetodoPagoResponse,
  TipoMetodoPago,
  ProveedorPago,
  TIPOS_METODO_PAGO,
  PROVEEDORES_PAGO,
  MONEDAS_SOPORTADAS,
  PAISES_DISPONIBLES,
} from './metodo-pago.interface';

// Variación Producto interfaces - Exportaciones específicas para evitar conflictos
export {
  VariacionProducto as VariacionProductoInterface,
  VariacionProductoSimple,
  ImagenVariacion,
  CreateVariacionProductoRequest,
  UpdateVariacionProductoRequest,
  VariacionProductoResponse,
  VariacionesProductoResponse,
  VariacionesByProductoResponse,
  VariacionProductoPagination,
  VariacionProductoFilters,
  VariacionProductoFormData,
  UpdateStockRequest,
  UpdateStockResponse,
  VariacionProductoApiError,
  VariacionProductoState,
  EstadoStock,
  OperacionStock,
  SortField,
  SortOrder,
} from './variacion-producto.interface';

// Imagen Producto interfaces - Exportaciones específicas para evitar conflictos
export {
  ImagenProducto as ImagenProductoInterface,
  ProductoBasico,
  VariacionBasica,
  ImagenMetadata,
  TipoImagen,
  CreateImagenProductoRequest,
  UpdateImagenProductoRequest,
  ImagenProductoFilters,
  ImagenProductoListResponse,
  ImagenProductoResponse,
  ImagenProductoByProductoResponse,
  ImagenProductoByVariacionResponse,
  UpdateOrderRequest,
  ImagenProductoStatistics,
  ImagenProductoStatisticsResponse,
  TIPOS_IMAGEN,
  IMAGEN_CONSTRAINTS,
  isValidImageType,
  isValidImageSize,
  getImageTypeDisplay,
} from './imagen-producto.interface';

// Exportar todas las interfaces de pedidos (básicas)
export * from './pedido.interface';

// FASE 3 - Sistema de Comercio - Interfaces avanzadas para gestión de pedidos
// Exportaciones específicas para evitar conflictos con pedido.interface.ts

// Detalle Pedido - Interfaces avanzadas
export {
  DetallePedido as DetallePedidoAvanzado,
  CreateDetallePedidoDto as CreateDetallePedidoAvanzadoDto,
  UpdateDetallePedidoDto,
  DetallePedidoFilters,
  DetallePedidoEstadisticas,
  DetallePedidoPaginatedResponse,
  DetallePedidoCalculos,
  ValidacionStock,
  UpdateMasivoDetallePedido,
  ResumenDetallePedido,
  TipoDescuentoDetalle,
  EstadoDetallePedido,
  ConfiguracionImpuesto,
  HistorialDetallePedido,
  ExportacionDetalles,
  DETALLE_PEDIDO_CONSTANTS,
  MonedaDetalle,
  CampoOrdenamiento,
  DireccionOrdenamiento,
} from './detalle-pedido.interface';

// Pago - Interfaces avanzadas (exportaciones específicas para evitar conflictos)
export {
  Pago as PagoCompleto,
  MetodoPago as MetodoPagoEnum,
  EstadoPago as EstadoPagoEnum,
  MetodoPagoInfo,
  PedidoInfo,
  UsuarioInfo,
  EstadoDetallado,
  MetodoDetallado,
  CreatePagoDto,
  UpdatePagoDto,
  PagoFilters,
  ResumenPagosPedido,
  PagoEstadisticas,
  ProcesarPagoRequest,
  DatosTarjeta,
  DatosTransferencia,
  DatosBilleteraDigital,
  DireccionFacturacion,
  ProcesarPagoResponse,
  ReembolsoRequest,
  ReembolsoResponse,
  ConfiguracionMetodoPago,
  ConciliacionPago,
  NotificacionPago,
  AuditoriaPago,
  PagoPaginatedResponse,
  PAGO_CONSTANTS,
  MonedaPago,
  MetodoRequiereAutorizacion,
  MetodoInstantaneo,
  EstadoFinal,
  EstadoExitoso,
  EstadoPendiente,
  EstadoFallido,
  CampoOrdenamientoPago,
  PagoUtils,
} from './pago.interface';

// Cuota Crédito - Interfaces avanzadas
export {
  CuotaCredito as CuotaCreditoAvanzada,
  EstadoCuota as EstadoCuotaAvanzada,
  CreateCuotaCreditoDto,
  UpdateCuotaCreditoDto,
  CuotaCreditoFilters,
  CuotaCreditoEstadisticas,
  CronogramaPagos,
  SimulacionCredito,
  PagoCuotaRequest,
  PagoCuotaResponse,
  RefinanciamientoRequest,
  CondonacionRequest,
  CalculoMora,
  ConfiguracionCredito,
  EvaluacionCrediticia,
  NotificacionCuota,
  ReporteCartera,
  CuotaCreditoPaginatedResponse,
  CUOTA_CREDITO_CONSTANTS,
  EstadoActivo,
  EstadoFinalCuota,
  MetodoCalculo,
  CampoOrdenamientoCuota,
  CuotaCreditoUtils,
} from './cuota-credito.interface';

// Dirección - Interfaces para gestión de direcciones de usuarios
export * from './direccion.interface';

// Comentario - Interfaces para gestión de comentarios de productos (exportaciones específicas para evitar conflictos)
export {
  Comentario as ComentarioCompleto,
  UsuarioComentario,
  ProductoComentario,
  CreateComentarioDto,
  UpdateComentarioDto,
  ComentarioFilters,
  ComentarioResponse,
  ComentarioSingleResponse,
  ComentariosByProductoResponse,
  EstadisticasProductoComentarios,
  EstadisticasComentarios,
  ComentarioOperationResponse,
  ResponderComentarioDto,
  CalificacionEnum,
  EstadoAprobacion,
  ComentarioValidation,
  ResumenComentarios,
  FiltrosRapidos,
  AccionMasivaComentarios,
  AccionMasivaResponse,
  COMENTARIO_CONSTANTS,
  ComentarioUtils,
} from './comentario.interface';

// Favorito - Interfaces para gestión de favoritos de usuarios
export * from './favorito.interface';

// Notificación - Interfaces para gestión de notificaciones del sistema (exportaciones específicas para evitar conflictos)
export {
  Notificacion as NotificacionCompleta,
  UsuarioNotificacion,
  TipoDetalladoNotificacion,
  TipoNotificacion,
  PrioridadNotificacion,
  CreateNotificacionDto,
  UpdateNotificacionDto,
  NotificacionFilters,
  NotificacionResponse,
  NotificacionSingleResponse,
  NotificacionesByUsuarioResponse,
  EstadisticasUsuarioNotificaciones,
  EstadisticasNotificaciones,
  NotificacionOperationResponse,
  MarcarLeidasRequest,
  MarcarLeidasResponse,
  LimpiarAntiguasRequest,
  LimpiarAntiguasResponse,
  EnviarMasivaRequest,
  EnviarMasivaResponse,
  NotificacionValidation,
  ResumenNotificaciones,
  FiltrosRapidosNotificaciones,
  AccionMasivaNotificaciones,
  AccionMasivaNotificacionesResponse,
  NOTIFICACION_CONSTANTS,
  TIPOS_NOTIFICACION_CONFIG,
  PRIORIDADES_CONFIG,
  TipoOrdenamientoNotificacion,
  DireccionOrdenamientoNotificacion,
  NotificacionUtils,
} from './notificacion.interface';

// Dashboard - Interfaces para el sistema de dashboard administrativo (exportaciones específicas para evitar conflictos)
export {
  // Tipos principales
  PeriodoDashboard,
  MonedaDashboard,
  TipoAgrupacion,
  OrdenamientoProducto,
  RolUsuario,
  TipoAlerta,
  PrioridadAlerta,
  TipoActividad,
  TipoCache,

  // Interfaces de datos principales
  FechasPeriodo,
  KPIsPrincipales,
  VentasPorEstado,
  VentasPorCanal,
  TendenciaDiariaVenta,
  EstadisticasVentas,
  ProductoMasVendido,
  EstadisticasProductos,
  TopCliente,
  EstadisticasUsuarios,
  PagosPorMetodo,
  EstadisticasFinancieras,
  ActividadReciente,
  AlertaSistema,
  ResumenDashboard,

  // Interfaces de respuesta
  DashboardResumenResponse,
  DashboardVentasResponse,
  DashboardProductosResponse,
  DashboardUsuariosResponse,
  DashboardFinancierasResponse,
  DashboardAlertasResponse,
  DashboardActividadResponse,
  LimpiarCacheResponse,
  DashboardErrorResponse,

  // Interfaces de filtros
  DashboardFiltros,
  VentasFiltros,
  ProductosFiltros,
  UsuariosFiltros,
  FinancierasFiltros,
  AlertasFiltros,
  ActividadFiltros,
  LimpiarCacheRequest,

  // Interfaces detalladas
  VentasPorPeriodo,
  AnalisisConversion,
  ComparacionPeriodo,
  EstadisticasVentasDetalladas,
  ResumenProductos,
  ProductoBajoStock,
  ProductoMejorCalificado,
  AnalisisCategorias,
  TendenciaPrecios,
  EstadisticasProductosDetalladas,
  ResumenUsuarios,
  NuevosRegistrosPorPeriodo,
  UsuarioMasActivo,
  AnalisisComportamiento,
  DistribucionGeografica,
  AnalisisRetencion,
  EstadisticasUsuariosDetalladas,
  ResumenFinanciero,
  FlujoCaja,
  AnalisisCreditos,
  AnalisisCupones,
  ProyeccionesFinancieras,
  EstadisticasFinancierasDetalladas,

  // Constantes y utilidades
  DASHBOARD_CONSTANTS,
  DASHBOARD_COLORS,
  DASHBOARD_ICONS,
  DashboardUtils,
} from './dashboard.interface';

// Reportes - Interfaces para el sistema de reportes administrativos (exportaciones específicas para evitar conflictos)
export {
  // Tipos principales
  TipoReporte,
  CategoriaReporte,
  FormatoExportacion,
  PeriodoReporte,
  MonedaReporte,
  AgrupacionReporte,
  EstadoPedidoReporte,
  CanalVentaReporte,
  SegmentacionCliente,
  ModuloPersonalizado,

  // Interfaces de datos principales
  MetadatosReporte,
  ReporteDisponible,
  ParametrosBaseReporte,
  ResumenVentas,
  VentasAgrupadas,
  ProductoMasVendidoReporte,
  AnalisisPorCanal,
  AnalisisPorMetodoPago,
  DetallePedidoReporte,

  // Interfaces de respuesta
  ListaReportesResponse,
  ReporteVentasResponse,
  ReporteInventarioResponse,
  ReporteClientesResponse,
  ReporteFinancieroResponse,
  ReportePersonalizadoResponse,
  EstadisticasReportesResponse,
  ExportacionResponse,
  ReporteErrorResponse,

  // Interfaces de filtros y parámetros
  ListaReportesFiltros,
  ParametrosReporteVentas,
  ParametrosReporteInventario,
  ParametrosReporteClientes,
  ParametrosReporteFinanciero,
  ParametrosReportePersonalizado,
  ParametrosEstadisticasReportes,

  // Interfaces de datos de reportes
  DatosReporteVentas,
  DatosReporteInventario,
  DatosReporteClientes,
  DatosReporteFinanciero,
  DatosReportePersonalizado,
  DatosEstadisticasReportes,

  // Interfaces específicas de inventario
  ResumenInventario,
  ProductoStockBajo,
  AnalisisCategoriasInventario,
  RotacionInventario,
  ValoracionInventario,
  ProductoInventario,

  // Interfaces específicas de clientes
  ResumenClientes,
  NuevosClientesPorPeriodo,
  SegmentacionClientesData,
  TopClienteReporte,
  AnalisisRetencionClientes,
  DistribucionGeograficaClientes,
  AnalisisComportamientoClientes,
  ClienteConCredito,

  // Interfaces específicas financieras
  ResumenFinancieroReporte,
  IngresosPorPeriodo,
  CuentasPorCobrar,
  AnalisisCuponesFinanciero,
  FlujoCajaReporte,
  ProyeccionesFinancierasReporte,
  IndicadoresFinancieros,

  // Interfaces de reportes personalizados
  ConfiguracionReportePersonalizado,

  // Interfaces de estadísticas
  EstadisticasGeneralesReportes,
  TendenciasReportes,
  ReporteMasGenerado,

  // Constantes y utilidades
  REPORTE_CONSTANTS,
  CATEGORIAS_REPORTES,
  ICONOS_REPORTES,
  COLORES_REPORTES,
  ReporteUtils,
} from './reporte.interface';

// Direcciones validadas - Exportaciones específicas para evitar conflictos
export {
  DireccionValidada as DireccionValidadaCompleta,
  EstadoValidacion,
  TipoValidacion,
  CreateDireccionValidadaRequest,
  UpdateDireccionValidadaRequest,
  DireccionValidadaFilters,
  DireccionValidadaResponse,
  DireccionValidadaListResponse,
  ValidarDireccionRequest,
  ValidarDireccionResponse,
  RevalidarDireccionesRequest,
  EstadisticasDireccionValidada,
} from './direccion-validada.interface';

// Adicionales - Sistema de gestión de adicionales para productos (exportaciones específicas para evitar conflictos)
export {
  Adicional,
  InformacionNutricional,
  EstadisticasAdicional,
  ProductoAdicional,
  GrupoAdicional,
  CreateAdicionalDto,
  UpdateAdicionalDto,
  FiltrosAdicional,
  AdicionalResponse,
  AdicionalesResponse,
  TipoAdicional,
  TipoAdicionalOption,
  TIPOS_ADICIONAL,
  ALERGENOS_COMUNES,
  esAdicionalVegetariano,
  esAdicionalVegano,
  tieneAlergenos,
  esAdicionalDisponible,
  calcularTiempoPreparacionTotal,
  calcularPrecioTotal,
  obtenerAdicionalesPorTipo,
  formatearCaracteristicasDieteticas,
} from './adicional.interface';

// Producto-Adicional - Sistema de relaciones entre productos y adicionales (exportaciones específicas para evitar conflictos)
export {
  ProductoAdicional as ProductoAdicionalRelacion,
  ProductoBasico as ProductoBasicoRelacion,
  AdicionalBasico,
  CreateProductoAdicionalDto,
  UpdateProductoAdicionalDto,
  FiltrosProductoAdicional,
  ProductoAdicionalResponse,
  ProductoAdicionalesResponse,
  EstadisticasProductoAdicional,
  ConfiguracionOrden,
  esProductoAdicionalObligatorio,
  obtenerPrecioEfectivo,
  formatearPrecio,
  obtenerTextoMaximoCantidad,
  validarProductoAdicional,
  calcularTotalAdicionales,
  agruparPorProducto,
  ordenarPorOrden,
  OPCIONES_ORDEN,
  DIRECCIONES_ORDEN,
  OpcionOrden,
  DireccionOrden,
} from './producto-adicional.interface';

// Grupo-Adicional - Sistema de gestión de grupos de adicionales (exportaciones específicas para evitar conflictos)
export {
  GrupoAdicional as GrupoAdicionalCompleto,
  AdicionalGrupo,
  ProductoGrupo,
  ReglasSeleccion,
  EstadisticasGrupo,
  CreateGrupoAdicionalDto,
  UpdateGrupoAdicionalDto,
  FiltrosGrupoAdicional,
  GrupoAdicionalResponse,
  GruposAdicionalesResponse,
  EstadisticasGrupoAdicional,
  ConfiguracionOrdenGrupo,
  TipoSeleccion,
  TIPOS_SELECCION,
  OPCIONES_ORDEN_GRUPO,
  DIRECCIONES_ORDEN_GRUPO,
  OpcionOrdenGrupo,
  DireccionOrdenGrupo,
  esGrupoObligatorio,
  esSeleccionMultiple,
  obtenerTipoSeleccion,
  obtenerTextoSeleccion,
  validarGrupoAdicional,
  validarSeleccionGrupo,
  calcularTotalAdicionalesGrupo,
  agruparPorTipo,
  ordenarPorOrden as ordenarGruposPorOrden,
  filtrarGruposActivos,
  filtrarGruposObligatorios,
  obtenerGruposConAdicionales,
  generarSlugDesdeNombre,
  formatearReglasSeleccion,
} from './grupo-adicional.interface';

// Adicional-Grupo - Sistema de relaciones entre adicionales y grupos (exportaciones específicas para evitar conflictos)
export {
  AdicionalGrupo as AdicionalGrupoRelacion,
  AdicionalDetalle,
  GrupoAdicionalDetalle,
  CreateAdicionalGrupoDto,
  UpdateAdicionalGrupoDto,
  FiltrosAdicionalGrupo,
  AdicionalGrupoResponse,
  AdicionalesGrupoResponse,
  EstadisticasAdicionalGrupo,
  ConfiguracionOrdenAdicionalGrupo,
  AdicionalPorGrupo,
  GrupoPorAdicional,
  OPCIONES_ORDEN_ADICIONAL_GRUPO,
  DIRECCIONES_ORDEN_ADICIONAL_GRUPO,
  OpcionOrdenAdicionalGrupo,
  DireccionOrdenAdicionalGrupo,
  validarAdicionalGrupo,
  validarRelacionExistente,
  obtenerSiguienteOrden,
  agruparPorGrupoAdicional,
  agruparPorAdicional,
  ordenarPorOrden as ordenarRelacionesPorOrden,
  filtrarPorGrupo,
  filtrarPorAdicional,
  obtenerAdicionalesDeGrupo,
  obtenerGruposDeAdicional,
  calcularEstadisticas as calcularEstadisticasAdicionalGrupo,
  reordenarRelaciones,
  validarOrdenUnico,
  normalizarOrdenes,
  formatearRelacion,
  buscarRelaciones,
} from './adicional-grupo.interface';

// Producto-Grupo-Adicional - Sistema de relaciones entre productos y grupos adicionales (exportaciones específicas para evitar conflictos)
export {
  ProductoGrupoAdicional,
  ProductoDetalle as ProductoDetalleGrupo,
  GrupoAdicionalDetalle as GrupoAdicionalDetalleProducto,
  AdicionalDetalle as AdicionalDetalleProductoGrupo,
  CreateProductoGrupoAdicionalDto,
  UpdateProductoGrupoAdicionalDto,
  FiltrosProductoGrupoAdicional,
  ProductoGrupoAdicionalResponse,
  ProductosGrupoAdicionalResponse,
  EstadisticasProductoGrupoAdicional,
  ConfiguracionOrdenProductoGrupo,
  GrupoPorProducto,
  ProductoPorGrupo,
  ConfiguracionProductoGrupo,
  OPCIONES_ORDEN_PRODUCTO_GRUPO,
  DIRECCIONES_ORDEN_PRODUCTO_GRUPO,
  ESTADOS_RELACION,
  OpcionOrdenProductoGrupo,
  DireccionOrdenProductoGrupo,
  EstadoRelacion,
  validarProductoGrupoAdicional,
  validarRelacionProductoGrupoExistente,
  obtenerSiguienteOrdenProducto,
  agruparPorProducto as agruparGruposPorProducto,
  agruparPorGrupoAdicional as agruparProductosPorGrupoAdicional,
  ordenarPorOrden as ordenarRelacionesProductoGrupoPorOrden,
  filtrarPorProducto as filtrarRelacionesPorProducto,
  filtrarPorGrupo as filtrarRelacionesPorGrupoAdicional,
  filtrarPorEstado as filtrarRelacionesPorEstado,
  obtenerGruposDeProducto,
  obtenerProductosDeGrupo,
  calcularEstadisticas as calcularEstadisticasProductoGrupoAdicional,
  reordenarRelacionesProducto,
  validarOrdenUnicoProducto,
  normalizarOrdenesProducto,
  toggleEstadoRelacion as toggleEstadoRelacionProductoGrupo,
  formatearRelacionProductoGrupo,
  buscarRelacionesProductoGrupo,
  obtenerConfiguracionProducto,
  validarConfiguracionProducto,
  clonarConfiguracionProducto,
  compararConfiguraciones,
} from './producto-grupo-adicional.interface';

// Detalle-Adicional - Sistema de gestión de detalles adicionales en pedidos
export {
  DetalleAdicional,
  DetallePedidoInfo,
  AdicionalInfo,
  DiferenciaPrecio,
  CreateDetalleAdicionalDto,
  UpdateDetalleAdicionalDto,
  FiltrosDetalleAdicional,
  DetalleAdicionalResponse,
  DetallesAdicionalesResponse,
  EstadisticasDetalleAdicional,
  AdicionalesPorDetallePedido,
  DetallesPorAdicional,
  ResumenPedidoAdicionales,
  OPCIONES_ORDEN_DETALLE_ADICIONAL,
  DIRECCIONES_ORDEN_DETALLE_ADICIONAL,
  TIPOS_ADICIONAL as TIPOS_ADICIONAL_DETALLE,
  OpcionOrdenDetalleAdicional,
  DireccionOrdenDetalleAdicional,
  TipoAdicional as TipoAdicionalDetalle,
  validarDetalleAdicional,
  calcularSubtotal,
  validarSubtotal,
  formatearPrecio as formatearPrecioDetalleAdicional,
  agruparPorDetallePedido,
  agruparPorAdicional as agruparDetallesPorAdicional,
  agruparPorPedido as agruparDetallesPorPedido,
  calcularEstadisticas as calcularEstadisticasDetalleAdicional,
  filtrarPorDetallePedido,
  filtrarPorAdicional as filtrarDetallesPorAdicional,
  filtrarPorPedido as filtrarDetallesPorPedido,
  filtrarPorTipoAdicional,
  filtrarConObservaciones,
  filtrarConDiferenciaPrecio,
  filtrarPorRangoPrecio,
  ordenarPorPrecio as ordenarDetallesPorPrecio,
  ordenarPorCantidad as ordenarDetallesPorCantidad,
  ordenarPorSubtotal,
  buscarDetallesAdicionales,
  obtenerTotalValorAdicionales,
  obtenerTotalCantidadAdicionales,
  obtenerPromedioValorPorDetalle,
  obtenerPromedioCantidadPorDetalle,
  formatearDetalleAdicional,
  validarConsistenciaPrecios,
  generarResumenDetallePedido,
} from './detalle-adicional.interface';

// SEO Producto - Sistema de gestión de SEO para productos
export * from './seo-producto.interface';

// Programación Entrega - Sistema de gestión de programación de entregas (exportaciones específicas para evitar conflictos)
export {
  ProgramacionEntrega as ProgramacionEntregaCompleta,
  TiempoTranscurrido,
  EstadoProgramacionInfo,
  PedidoProgramacion,
  RepartidorProgramacion,
  TiemposEntrega as TiemposEntregaCompleta,
  InfoRuta,
  ResumenRuta,
  RutaRepartidorResponse,
  CreateProgramacionEntregaDto,
  UpdateProgramacionEntregaDto,
  CambiarEstadoDto as CambiarEstadoProgramacionDto,
  ReprogramarEntregaDto,
  RutaRepartidorDto,
  FiltrosProgramacionEntrega,
  PaginacionProgramacionEntrega,
  ProgramacionEntregaResponse,
  EstadoProgramacion as EstadoProgramacionEntrega,
  TipoPuntualidad,
  EstadoRuta,
  ESTADOS_PROGRAMACION,
  ESTADOS_PROGRAMACION_COLORES,
  ESTADOS_PROGRAMACION_BADGES,
  ESTADOS_RUTA_COLORES,
  TRANSICIONES_VALIDAS,
  obtenerEstadoTexto,
  obtenerEstadoColor,
  obtenerEstadoBadge,
  obtenerColorEstadoRuta,
  formatearTiempo as formatearTiempoProgramacion,
  formatearVentanaEntrega,
  formatearFecha as formatearFechaProgramacion,
  formatearHora as formatearHoraProgramacion,
  esProgramacionFutura,
  esProgramacionHoy,
  esProgramacionPasada,
  estaEnVentana,
  esVentanaExpirada,
  requiereAtencion as requiereAtencionProgramacion,
  esEntregaExitosa,
  tieneRetraso,
  calcularDuracionVentana,
  calcularTiempoTranscurrido,
  calcularTiempoTotalEntrega,
  obtenerPuntualidad,
  esTransicionValida,
  obtenerTransicionesPosibles,
  agruparPorEstado as agruparProgramacionesPorEstado,
  agruparPorRepartidor,
  agruparPorFecha as agruparProgramacionesPorFecha,
  filtrarPorEstado as filtrarProgramacionesPorEstado,
  filtrarPorRepartidor,
  filtrarPorFecha as filtrarProgramacionesPorFecha,
  filtrarQueRequierenAtencion,
  filtrarEntregasHoy,
  filtrarEntregasPendientes,
  ordenarPorRuta,
  ordenarPorFecha as ordenarProgramacionesPorFecha,
  buscarProgramaciones,
  obtenerEstadisticasRuta,
  validarVentanaEntrega,
  validarFechaProgramacion,
} from './programacion-entrega.interface';

// Métrica Negocio - Sistema de métricas y análisis de negocio
export * from './metrica-negocio.interface';

// Promoción - Sistema de gestión de promociones y descuentos
export * from './promocion.interface';

// Inventario Movimiento - Sistema de gestión de movimientos de inventario
export * from './inventario-movimiento.interface';

// Carrito Temporal - Sistema de gestión de carrito temporal de compras
export * from './carrito-temporal.interface';
